### PR TITLE
Adding support for Recently Watched and Bookmarks

### PR DESCRIPTION
**Pull request by josharrington**
Hi guys,

Thanks for the great Pluralsight addon! Recently, Microsoft annouced you can get 6 months of Pluralsight for free when you sign up for Visual Studio Dev Essentials. I signed up and checked out your addon. I wanted to be able to view the most recent things I've viewed on other devices and to also be able to bookmark a course on the Pluralsight website and start watching in Kodi without having to search or find it in the course list. These features have been added in this pull request. 

Thanks again!

### CODE REVIEW

**Comment by josharrington** [comment]
In addition, there is some basic support for stepping down the video quality if a certain clip is lacking a higher video quality altogether. In the courses I tried, this seemed to work well. There shouldn't be any courses that do not work because it will step down to 1024x768, which before was the only quality available as it was hardcoded.

**Comment by supertom44** [comment]
Hi,

Thanks for your contribution, the bookmarks feature is something I have wanted to add ever since Pluralsight added it to their site.

The dynamic resolution and recently viewed are nice additions too.

Cheers.

**Comment by mintsoft** [comment]
@papersackpuppet This has been released as 1.1.0 which should be available from Kodi now. 

Thanks

**Comment by josharrington** [comment]
Woot! Thanks guys

**Pull request merged**
